[package]
name = "beep"
version = "0.1.0"
authors = ["Sigurd Holsen <sigurd.holsen@cognite.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.8.1"
rodio = "0.16.0"
